sudo: false
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.3.1
before_install:
  - gem update --system
  - gem --version
deploy:
  provider: script
  script: scripts/deploy.sh
  github_token: $GH_TOKEN
  skip_cleanup: true
  on:
    branch: master
