sudo: false
dist: trusty
language: ruby
rvm:
  - 2.6.8
cache:
  directories:
  - $HOME/tmp/.htmlproofer #https://github.com/gjtorikian/html-proofer/issues/381
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
deploy:
  provider: script
  script: scripts/deploy.sh
  github_token: $GH_TOKEN
  skip_cleanup: true
  on:
    branch: master
