openapi: 3.0.4
info:
  title: Transfers API - 1.1 (Draft)
  version: 1.0.0

paths:
  /v1/transfers/search:
    get:
      summary: Search for available transfers
      description: Returns a list of available transfers based on pick-up and drop-off details
      parameters:
        Please refer to the parameters section in the existing documentation for details
      responses:
        Please refer to the responses section in the existing documentation for details

  /v1/transfers/{productCode}:
    post:
      summary: Book a transfer
      description: Create a booking for a given transfer product
      parameters:
        Please refer to the parameters section in the existing documentation for details
      responses:
        Please refer to the responses section in the existing documentation for details

  /v1/transfers/booking/{bookingRef}:
    get:
      summary: Retrieve booking details (future)
      description: Get full information about an existing booking
      parameters:
        - name: bookingRef
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Booking details successfully retrieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Booking:
                    type: object
                    properties:
                      BookingRef:
                        type: string
                        example: "BookingRef"
                      SupplierRef:
                        type: string
                        example: "SupplierReference"
                      VoucherRef:
                        type: string
                      BookingStatus:
                        type: string
                        example: "PENDING"
                      DateBooked:
                        type: string
                        format: date
                      DateCancelled:
                        type: string
                        format: date
                        nullable: true
                      Amendable:
                        type: string
                        example: "N"
                      BookingProduct:
                        type: object
                        description: Product details for the booking
                        properties:
                          Code:
                            type: string
                            example: "ProductCode"
                          Name:
                            type: string
                            example: "Private Minibus Transfer (1 -7 People)"
                          SalesCurrency:
                            type: string
                            example: "GBP"
                          Price:
                            type: number
                            example: 27665
                          Category:
                            type: string
                            example: "Private Minibus Transfer (1 -7 People)"
                          TransferCode:
                            type: string
                            example: "TransferCode"
                          DeparturePointType:
                            type: string
                            example: "DeparturePointType"
                          ArrivalPointType:
                            type: string
                            example: "ArrivalPointType"
                          Cancellation:
                            type: object
                            properties:
                              Period:
                                type: integer
                                example: 48
                              Fee:
                                type: number
                                example: 0
                          VehicleDetails:
                            type: object
                            properties:
                              MinCapacity:
                                type: integer
                                example: 1
                              MaxCapacity:
                                type: integer
                                example: 7
                              IsPrivate:
                                type: boolean
                                example: true
            application/xml:
              schema:
                type: object
                xml:
                  name: Booking
                properties:
                  BookingRef:
                    type: string
                    example: "BookingRef"
                    xml:
                      name: BookingRef
                  SupplierRef:
                    type: string
                    example: "SupplierReference"
                    xml:
                      name: SupplierRef
                  VoucherRef:
                    type: string
                    xml:
                      name: VoucherRef
                  BookingStatus:
                    type: string
                    example: "PENDING"
                    xml:
                      name: BookingStatus
                  DateBooked:
                    type: string
                    format: date
                    xml:
                      name: DateBooked
                  DateCancelled:
                    type: string
                    format: date
                    nullable: true
                    xml:
                      name: DateCancelled
                  Amendable:
                    type: string
                    example: "N"
                    xml:
                      name: Amendable
                  BookingProduct:
                    type: object
                    xml:
                      name: BookingProduct
                    properties:
                      Code:
                        type: string
                        example: "ProductCode"
                        xml:
                          name: Code
                      Name:
                        type: string
                        example: "Private Minibus Transfer (1 -7 People)"
                        xml:
                          name: Name
                      SalesCurrency:
                        type: string
                        example: "GBP"
                        xml:
                          name: SalesCurrency
                      Price:
                        type: number
                        example: 27665
                        xml:
                          name: Price
                      Category:
                        type: string
                        example: "Private Minibus Transfer (1 -7 People)"
                        xml:
                          name: Category
                      DeparturePointType:
                        type: string
                        example: "DeparturePointType"
                        xml:
                          name: DeparturePointType
                      ArrivalPointType:
                        type: string
                        example: "ArrivalPointType"
                        xml:
                          name: ArrivalPointType
                      Cancellation:
                        type: object
                        xml:
                          name: Cancellation
                        properties:
                          Period:
                            type: integer
                            example: 48
                            xml:
                              name: Period
                          Fee:
                            type: number
                            example: 0
                            xml:
                              name: Fee
                      VehicleDetails:
                        type: object
                        xml:
                          name: VehicleDetails
                        properties:
                          MinCapacity:
                            type: integer
                            example: 1
                            xml:
                              name: MinCapacity
                          MaxCapacity:
                            type: integer
                            example: 7
                            xml:
                              name: MaxCapacity
                          IsPrivate:
                            type: boolean
                            example: true
                            xml:
                              name: IsPrivate
        '400':
          description: Invalid booking reference format.
        '404':
          description: Booking not found.
        '500':
          description: Internal server error.


    delete:
      summary: Cancel a booking (future)
      description: Cancel an existing booking for a given booking reference
      parameters:
        - name: bookingRef
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Booking cancelled successfully. No content returned.
        '400':
          description: Bad request. Booking reference is missing or invalid.
        '404':
          description: Booking not found for the given reference.
        '409':
          description: Booking cannot be cancelled (e.g. already used or past deadline).
        '500':
          description: Internal server error.

  /v1/transfers/booking/{bookingRef}/cancellation-policy:
    get:
      summary: Check if booking can be cancelled (future)
      description: Returns the cancellation eligibility or policy for a given booking
      parameters:
        - name: bookingRef
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Returns whether the booking is cancellable and any applicable cancellation policy.
        '400':
          description: Invalid or missing booking reference.
        '404':
          description: Booking not found.
        '500':
          description: Internal server error.


  /v1/transfers/{productCode}/content:
    get:
      summary: Get transfer product content (future)
      description: Returns content like descriptions, images, etc. for a given transfer product
      parameters:
        - name: productCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Transfer product content successfully retrieved.
        '400':
          description: Invalid product code.
        '404':
          description: Transfer product not found.
        '500':
          description: Internal server error.

